# -*- coding: utf-8 -*-
"""Training&TestingML_Algorithm_For_Energy_Meter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tRUEgaHnsUkN_JDLW7b-rDVQA6nqMrxW
"""

from pandas import read_csv
from sklearn.model_selection import train_test_split
#from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

filename = 'Energy Meter.csv'
names = ['Voltage','Current','Power','class']
data = read_csv(filename, names = names)

arrey = data.values
X = arrey[:,0:3]
Y = arrey[:,3]
X_train, X_val, Y_train, Y_val = train_test_split(X, Y, test_size = 0.20, random_state = 1)
#model = SVC(gamma = 'auto')
model = LogisticRegression(solver = 'liblinear', multi_class = 'ovr')

model.fit(X_train, Y_train)

import pickle
filename = 'finalized_model.pkl'
pickle.dump(model, open(filename, 'wb'))

loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_val, Y_val)
print(result)

value = [[211.58159999999998, 0.1176985, 37.446769476]]
predictions = model.predict(value)
print(predictions[0])